[project]
name = "llmaixweb"
version = "0.1.2"
description = "LLM Information Extraction Web Application"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.117.1",
    "uvicorn>=0.37.0",
    "pyjwt~=2.10.1",
    "sqlalchemy~=2.0.43",
    "psycopg[binary,pool]>=3.2.10",
    "pydantic_settings~=2.10.1",
    "openai~=1.109.0",
    "bcrypt~=4.3.0",
    "boto3~=1.40.37",
    "boto3-stubs==1.40.46",
    "llmaix[marker,docling,paddleocr]~=0.0.26",
    "redis~=6.4.0",
    "celery~=5.5.3",
    "jsonschema~=4.25.1",
    "thefuzz>=0.22.1",
    "pandas>=2.3.2",
    "pandas-stubs>=2.3.0.250827",
    "xlsxwriter>=3.2.9",
    "celery-types==0.23.0",
]

[dependency-groups]
dev = [
    "ruff>=0.13.1",
    "ty>=0.0.1a21",
    "pytest>=8.4.2",
    "pytest-cov~=7.0.0",
    "isort~=6.0.1",
]