[project]
name = "llmaixweb"
version = "0.1.2"
description = "LLM Information Extraction Web Application"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.121.0",
    "uvicorn>=0.38.0",
    "pyjwt~=2.10.1",
    "sqlalchemy~=2.0.44",
    "psycopg[binary,pool]>=3.2.12",
    "pydantic_settings~=2.11.0",
    "openai~=1.109.1",
    "bcrypt~=5.0.0",
    "boto3~=1.40.69",
    "boto3-stubs==1.40.69",
    "llmaix[marker,docling,paddleocr]~=0.0.26",
    "redis~=7.0.1",
    "celery~=5.5.3",
    "jsonschema~=4.25.1",
    "thefuzz>=0.22.1",
    "pandas>=2.3.3",
    "pandas-stubs>=2.3.2.250926",
    "xlsxwriter>=3.2.9",
    "celery-types==0.23.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.4",
    "ty>=0.0.1a25",
    "pytest>=9.0.0",
    "pytest-cov~=7.0.0",
    "isort~=7.0.0",
]